---
- name: Cisco VLAN Übersicht
  hosts: cisco_switches
  gather_facts: false

  vars:
    ansible_command_timeout: 120

  tasks:
    - name: VLAN Informationen auslesen
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: result

    - name: Header anzeigen
      ansible.builtin.debug:
        msg:
          - "===================================="
          - "Switch: {{ inventory_hostname }}"
          - "IP: {{ ansible_host }}"
          - "===================================="

    - name: VLAN Übersicht anzeigen
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: >-
        {{
          result.stdout_lines[0]
          | select('match', '^[0-9]+')
          | reject('search', '^1002 ')
          | reject('search', '^1003 ')
          | reject('search', '^1004 ')
          | reject('search', '^1005 ')
          | list
        }}
