---
- name: Cisco Facts
  hosts: cisco_switches
  gather_facts: false

  tasks:
    - name: Show IP Interface Brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: result

    - name: Ausgabe
      debug:
        var: result.stdout_lines
